### PR TITLE
github: workflows: add common-* workflows

### PR DESCRIPTION
**Pull request by paivin-dn**
## Motivation
To simplify updating and reworking workflow I've added the following common* workflows:
- common-pull-request -  combine all the workflows we use in pull_request events into one workflow.
- common-pull-request-labeled - combine all the workflows we use in pull_request(labeled) events into one workflow.
- pull-request-unlabeled-closed - combine all the workflows we use in pull_request(unlabeled, closed) events into one workflow.
- common-deploy-dev - combine all the workflows we use in push to branch events into one workflow.
- common-deploy-release - combine all the workflows we use in release.published event into one workflow.

These workflows combine other workflows from this repository.

## Checklist

<details open=true>
  <summary>PR checklist (self-check before review)</summary>

- [X] The branch name fits the `pr-<prefix>-<task-name>` pattern;
- [X] The PR has a meaningful name using the `<prefix>: <description>` pattern;
- [X] The PR is properly labeled depending on the change;
- [X] The PR is assigned to you;
- [X] If the PR is based on another PR, links to them are added to the PR header and the "has PR dependency" label is set;
- [X] Self-review. Review your code, commits, and the PR description;
- [X] Make sure that you updated the corresponding docs in the `docs/` directory;
- [X] Links to the updated docs are added to the PR header (if any);
- [X] CI successfully finished;

</details>

### CODE REVIEW

**Review by glebignatieff — APPROVED** [review]
GJ!

<details>
  <summary>That's how I see this PR</summary>

monkie-kid-lego-monkie-kid

</details>

**Comment by glebignatieff** [comment]
As an optional suggestion, I'd say we could group these workflows in a `common` folder, for instance. I believe that would make it a little less cluttered.

And speaking of naming, I'd suggest considering `base` prefix as an alternative, as `common` typically means that it's included in other WFs rather than vice versa. As an example why `base` would make sense, we could consider https://github.com/emlid/cloud-telemetry/pull/31, where we have `common-pull-request` as a base which is then extended with `tests`.

**Review by iamsaywhat — APPROVED** [review]
GJ!

**Comment by paivin-dn** [comment]
> As an optional suggestion, I'd say we could group these workflows in a `common` folder, for instance. I believe that would make it a little less cluttered.
> 
> And speaking of naming, I'd suggest considering `base` prefix as an alternative, as `common` typically means that it's included in other WFs rather than vice versa. As an example why `base` would make sense, we could consider [emlid/cloud-telemetry#31](https://github.com/emlid/cloud-telemetry/pull/31), where we have `common-pull-request` as a base which is then extended with `tests`.

1. Unfortanly we couldn't put workflows in a nested directory([here](https://github.com/community/community/discussions/10773) is the feature request) =(
2. I think, you are right and the `base` prefix is more suitable.

**Pull request merged**
